##
## Build instructions
##
all:
	cd shallowwater_sphere; make
	cd nonhydro_xz; make
	cd nonhydro_sphere; make

clean:
	cd shallowwater_sphere; make clean
	cd nonhydro_xz; make clean
	cd nonhydro_sphere; make clean
